name: Experimental Cron job


on:
  schedule:
    - cron: "0 21 * * *"  # runs daily (UTC time)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last updated: $(date)" >> log1.txt
      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "updates" || exit 0
          git push
       
      - name: final commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git rm -f log1.txt
          git commit -m "autonomous commit " || exit 0
          git push   